### ISSUE TITLE
Interface Support for Yaml Parser?

### ISSUE THREAD

**Issue by alex-plouff** [webcompere/lightweight-config#19]
Any plans to auto-detect implementations of an interface?

It would be nice to have the yaml parser auto-detect implementations of an interface or be able to tell the yaml parser which implementation of an interface to use.

For example, given the yaml below:
```
profiles:
  local:
    prop1: x
  staging:
    prop1: y
  ```
It would be nice to have the corresponding Java class for `local` and `staging` be based on an interface.
```
public class Profile implements IProfile {
  String prop1;
  ...etc...
}
  ```

Is this currently supported?
Currently the parser fails in this scenario using the latest version 1.3.0.

**Comment by ashleyfrieze** [comment]
Lightweight config uses SnakeYml as its deserialisation layer. I don't think SnakeYml will ever support type detection like this.

Perhaps try following the instructions to make a custom tag in the yml and tag the precise type you want to load.

Or use the concrete type, rather than interface type in your configuration class.

If you can provide more of an example of what you're trying to do, and if there are up votes, I might be able to demonstrate this with a test case.

**Comment by ashleyfrieze** [comment]
@alex-plouff any updates on this?
